name: Deploy Next.js to AWS S3

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Build the project
      run: npm run build

    - name: Deploy to S3
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AKIAVRUVQ6PSVXRP2CET }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.h6kTzCa6rB/WNmtE2/CKh5Xg4EL0MBz0sDlMwY79 }}
        AWS_REGION: 'eu-north-1'
        S3_BUCKET: 'deepika2616'
      run: |
        npm install -g aws-cli
        aws s3 sync out/ s3://$S3_BUCKET --delete
